copyright: Kirill Solovei &copy; 2023–2025

extra:
  analytics:
    provider: google
    property: G-E9FSFDM6ER
  social:
    - icon: fontawesome/solid/square-rss
      link: /feed.xml
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hatedabamboo/
    - icon: fontawesome/brands/github
      link: https://github.com/hatedabamboo/
    - icon: fontawesome/brands/telegram
      link: https://t.me/hatedabamboo/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@hatedabamboo

markdown_extensions: 
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

plugins:
  - blog:
      archive: true
      archive_date_format: YYYY
      blog_dir: .
      pagination: true
      pagination_per_page: 10
      post_date_format: long
      post_dir: posts
      post_excerpt: required
      post_url_format: "{slug}"
  - glightbox:
      touchNavigation: true
      draggable: false
  - rss:
      categories:
        - tags
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      feeds_filenames:
        rss_created: feed.xml
      match_path: "posts/.*"
  - social:
      cards: true
      cards_layout_options:
        font_family: Roboto
  - tags

site_author: Kirill Solovei
site_description: Personal notes on AWS, DevOps, Linux, and Systems Engineering
site_name: hatedabamboo notes
site_url: https://notes.hatedabamboo.me

theme:
  custom_dir: overrides
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
  font:
    text: Open Sans
  icon:
    logo: material/note-edit-outline
    next: fontawesome/solid/angle-right
    previous: fontawesome/solid/angle-left
    top: fontawesome/solid/angle-up
  name: material
  palette:
    primary: white
    accent: light blue
